name: Event Name Detector

on:
  workflow_dispatch:   
  push:                
  pull_request:       

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show event trigger
        run: echo "I've been triggered by ${{ github.event_name }} event"
